# Generated by Django 5.1 on 2024-11-06 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autenticacion.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_tablero', models.IntegerField(choices=[(1, 'Por hacer'), (2, 'En proceso'), (3, 'Hecho')])),
                ('id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.secciones')),
            ],
        ),
    ]
